TesteFood/TesteFood/Entities/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TesteFood.Entities
{
	public class Contact
	{
		public int ContactID { get; set; }
		public string ContactName { get; set; }
		public string ContactEmail { get; set; }
		public string ContactSubject { get; set; }
		public string ContactMessage { get; set; }
		public DateTime ContactSendDate { get; set; }
		public bool IsRead { get; set; }
	}
}

TesteFood/TesteFood/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TesteFood.Context;
using TesteFood.Entities;

namespace TesteFood.Controllers
{
    public class ContactController : Controller
    {
        TasteContext context = new TasteContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(Contact p) // index degilde contact olacaktı ama olsun :)
        {
            var value = context.Contacts.Add(p);
            value.ContactName = p.ContactName;
            value.ContactEmail = p.ContactEmail;
            value.ContactSubject = p.ContactSubject;
            value.ContactMessage = p.ContactMessage;
            value.ContactSendDate = DateTime.Today;
            context.SaveChanges();
            return View();
        }

        public ActionResult PartialContact()
        {
            var values = context.Adresses.ToList();   
            return PartialView(values);
        }
    }
}

TesteFood/TesteFood/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TesteFood.Context;
using TesteFood.Entities;

namespace TesteFood.Controllers
{
    public class DefaultController : Controller
    {
        TasteContext context = new TasteContext();
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }

        public PartialViewResult PartialNavbarInfo()
        {
            ViewBag.phone = context.Adresses.Select(x => x.AdressPhone).FirstOrDefault();
            ViewBag.mail = context.Adresses.Select(x => x.AdressEmail).FirstOrDefault();
            ViewBag.description = context.Adresses.Select(x => x.AdressDescription).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }

        public PartialViewResult PartialSlider()
        {
            return PartialView();
        }
        public PartialViewResult PartialAbout()
        {
            var value = context.Abouts.ToList();
            return PartialView(value);
        }

        public PartialViewResult PartialMenu()
        {
            var values = context.Products.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialTestimonial()
        {
            var value = context.Testimonials.ToList();
            return PartialView(value);
        }

        public PartialViewResult PartialChef()
        {
            var value = context.Chefs.ToList();
            return PartialView(value);
        } 
        
        public PartialViewResult PartialFooter()
        {
            // footerın en alt kısımdaki çalışma saatlerini cektim
            var value = context.OpenDayHours.ToList();
            return PartialView(value);
        }

        public PartialViewResult PartialNavigation()
        {
            return PartialView();
        }


    }
}

TesteFood/TesteFood/Views/Contact/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutMenu.cshtml";
}




@Html.Action("PartialContact", "Contact")


<section class="ftco-section ftco-no-pt contact-section">
    <div class="container">
        <div class="row d-flex align-items-stretch no-gutters">
            <div class="col-md-12 p-5 order-md-last">
                <h2 class="h1 mb-5 font-weight-bold text-center">Şikayet ve Önerileriniz için Bize Yazın</h2>
                @using (Html.BeginForm("Index", "Contact", FormMethod.Post))
                {

                    <form method="post">
                        <div class="form-group">
                            <input type="text" class="form-control" name="ContactName" placeholder="Adınız.." required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="ContactEmail" placeholder="Mail Adresiniz.." required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="ContactSubject" placeholder="Konu.." required>
                        </div>
                        <div class="form-group">
                            <textarea name="ContactMessage" id="" cols="30" rows="7" class="form-control" required placeholder="Mesajınız.."></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Mesaj Gönder" class="btn btn-primary py-3 px-5 ">
                        </div>
                    </form>
                }
            </div>
            @*<div class="col-md-6 d-flex align-items-stretch">
                    <div id="map"></div>
                </div>*@
        </div>
    </div>
</section>

@Html.Action("PartialNavigation","Default")

TesteFood/TesteFood/Views/Contact/PartialContact.cshtml
@model List<TesteFood.Entities.Adress>

<section class="ftco-section contact-section bg-light">
    <div class="container">


        <div class="row d-flex contact-info">
            <div class="col-md-12">
                <h2 class="h1 font-weight-bold text-center">Iletisim Bilgilerimiz</h2>
            </div>
            @foreach (var x in Model)
            {
                <div class="w-100"></div>
                <div class="col-md-3 d-flex">
                    <div class="dbox">
                        <p><span>Address:</span> @x.AdressDescription </p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="dbox">
                        <p><span>Telefon:</span> <a href="">@x.AdressPhone</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="dbox">
                        <p><span>Email:</span> <a href="">@x.AdressEmail</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="dbox">
                        <p><span>Website</span> <a href="#">yoursite.com</a></p>
                    </div>
                </div>
            }
        </div>

    </div>
</section>